server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_db
    username: postgres
    password: Sairat@00p
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1